global.KB_KEYCODE_ALIASES = [];

for (var i = ord("0"); i <= ord("Z"); i++) 
{
	global.KB_KEYCODE_ALIASES[i] = chr(i);
}

global.KB_KEYCODE_ALIASES[0] = "No Key";
global.KB_KEYCODE_ALIASES[8] = "Backspace";
global.KB_KEYCODE_ALIASES[9] = "Tab";
global.KB_KEYCODE_ALIASES[13] = "Enter";
global.KB_KEYCODE_ALIASES[16] = "Shift";
global.KB_KEYCODE_ALIASES[17] = "Ctrl";
global.KB_KEYCODE_ALIASES[vk_alt] = "Alt";
global.KB_KEYCODE_ALIASES[vk_pause] = "Pause/Break";
global.KB_KEYCODE_ALIASES[20] = "Caps Lock";
global.KB_KEYCODE_ALIASES[27] = "Esc";
global.KB_KEYCODE_ALIASES[33] = "Page Up";
global.KB_KEYCODE_ALIASES[34] = "Page Down";
global.KB_KEYCODE_ALIASES[35] = "End";
global.KB_KEYCODE_ALIASES[36] = "Home";
global.KB_KEYCODE_ALIASES[37] = "Left Arrow";
global.KB_KEYCODE_ALIASES[38] = "Up Arrow";
global.KB_KEYCODE_ALIASES[39] = "Right Arrow";
global.KB_KEYCODE_ALIASES[40] = "Down Arrow";
global.KB_KEYCODE_ALIASES[45] = "Insert";
global.KB_KEYCODE_ALIASES[46] = "Delete";
global.KB_KEYCODE_ALIASES[96] = "Numpad 0";
global.KB_KEYCODE_ALIASES[97] = "Numpad 1";
global.KB_KEYCODE_ALIASES[98] = "Numpad 2";
global.KB_KEYCODE_ALIASES[99] = "Numpad 3";
global.KB_KEYCODE_ALIASES[100] = "Numpad 4";
global.KB_KEYCODE_ALIASES[101] = "Numpad 5";
global.KB_KEYCODE_ALIASES[102] = "Numpad 6";
global.KB_KEYCODE_ALIASES[103] = "Numpad 7";
global.KB_KEYCODE_ALIASES[104] = "Numpad 8";
global.KB_KEYCODE_ALIASES[105] = "Numpad 9";
global.KB_KEYCODE_ALIASES[106] = "Numpad *";
global.KB_KEYCODE_ALIASES[107] = "Numpad +";
global.KB_KEYCODE_ALIASES[109] = "Numpad -";
global.KB_KEYCODE_ALIASES[110] = "Numpad .";
global.KB_KEYCODE_ALIASES[111] = "Numpad /";
global.KB_KEYCODE_ALIASES[112] = "F1";
global.KB_KEYCODE_ALIASES[113] = "F2";
global.KB_KEYCODE_ALIASES[114] = "F3";
global.KB_KEYCODE_ALIASES[115] = "F4";
global.KB_KEYCODE_ALIASES[116] = "F5";
global.KB_KEYCODE_ALIASES[117] = "F6";
global.KB_KEYCODE_ALIASES[118] = "F7";
global.KB_KEYCODE_ALIASES[119] = "F8";
global.KB_KEYCODE_ALIASES[120] = "F9";
global.KB_KEYCODE_ALIASES[121] = "F10";
global.KB_KEYCODE_ALIASES[122] = "F11";
global.KB_KEYCODE_ALIASES[123] = "F12";
global.KB_KEYCODE_ALIASES[144] = "Num Lock";
global.KB_KEYCODE_ALIASES[145] = "Scroll Lock";
global.KB_KEYCODE_ALIASES[186] = ";";
global.KB_KEYCODE_ALIASES[187] = "=";
global.KB_KEYCODE_ALIASES[188] = ",";
global.KB_KEYCODE_ALIASES[189] = "-";
global.KB_KEYCODE_ALIASES[190] = ".";
global.KB_KEYCODE_ALIASES[191] = "\\";
global.KB_KEYCODE_ALIASES[192] = "`";
global.KB_KEYCODE_ALIASES[219] = "/";
global.KB_KEYCODE_ALIASES[220] = "[";
global.KB_KEYCODE_ALIASES[221] = "]";
global.KB_KEYCODE_ALIASES[222] = "'";