enum INTERACTION_TYPE {
	CONFIRM,
	INPUT_CONFIRM
}
enum INTERACTION_STATUS {
	OFF,
	HOLD,
	PRESSED,
	RELEASED
}

function ACTION_INTERACTIONS_CONFIG()
{
	var INTERACTION_KEYS = {
		SHIFT: new INTERACTION_MAPPING_KEY_KEYBOARD(vk_shift),
		ENTER: new INTERACTION_MAPPING_KEY_KEYBOARD(vk_enter),
		// Z: new INTERACTION_MAPPING_KEY_KEYBOARD(ord("Z")),
		X: new INTERACTION_MAPPING_KEY_KEYBOARD(ord("X"))
	};
	global.INTERACTION_MAPPINGS = new INTERACTION_MAPPINGS();
	global.INTERACTION_MAPPINGS.SET_MAPPING(
		INTERACTION_TYPE.CONFIRM,
		new INTERACTION_MAPPING([INTERACTION_KEYS.SHIFT, INTERACTION_KEYS.X])
	);
	global.INTERACTION_MAPPINGS.SET_MAPPING(
		INTERACTION_TYPE.INPUT_CONFIRM,
		new INTERACTION_MAPPING([INTERACTION_KEYS.ENTER]) // , INTERACTION_KEYS.Z])
	);
}